//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetExpenceProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string PaymentMethod { get; set; }
        public string Note { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Login Login { get; set; }
    }
}
